# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 01:22
from __future__ import unicode_literals

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('nimbus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='', help_text='Provide a unique slug for this team member', max_length=64, verbose_name='slug')),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image of this partner', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('info', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='info_team_member', to='cms.Placeholder')),
            ],
        ),
    ]
