# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus', '0002_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='info',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
