# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('nimbus', '0003_auto_20190109_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_profile', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image of this partner', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'members',
            },
        ),
    ]
